name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'mtb-microfrontends-workshop'
    runs-on: ubuntu-latest
    steps:
      - id: update-import-map
        run: |
          curl -u ${{ secrets.IMD_USERNAME }}:${{ secrets.IMD_PASSWORD }} --data "@mtb.importmap" -X PATCH ${{ secrets.IMD_ORIGIN }}/import-map.json?env=mtb -H "Accept: application/json" -H "Content-Type: application/json" --fail